// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile =  {
    "aws_project_region": "eu-west-1",
    "aws_cognito_identity_pool_id": "eu-west-1:773baa56-cff0-4484-8d77-8c22bf5047dc",
    "aws_cognito_region": "eu-west-1",
    "aws_user_pools_id": "eu-west-1_EOb6oKthf",
    "aws_user_pools_web_client_id": "377eb2q869prq3r037t7e1js1f"
};


export default awsmobile;
